"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var digits = [];
digits.push(2);
digits.push(4);
var names = [];
names.push("fahad");
names.push("ali");
var users = [];
users.push({ name: "ali", isActive: false });
console.log(names, digits, users);
